spring:
    profiles:
        active: dev

logging:
    level:
        com.example.meimeiss.dao: debug

#mybatis
mybatis:
    type-aliases-package: com.example.meimeiss.model
    mapperLocations: classpath:mapper/*Mapper.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl